In [1]:
import numpy as np

In [2]:
#1
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [3]:
#2
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [6]:
#3
s=np.array([10,20,30,40,50,60]).reshape(2,3)
s

array([[10, 20, 30],
       [40, 50, 60]])

In [8]:
#3a
s.size

6

In [9]:
#3b
s.dtype

dtype('int32')

In [10]:
#4
a=np.array([1,2,3])
b=np.array([4,5,6])

In [11]:
#4a
a+b

array([5, 7, 9])

In [12]:
#4b
a-b

array([-3, -3, -3])

In [13]:
#4c
a*b

array([ 4, 10, 18])

In [14]:
#4d
a/b

array([0.25, 0.4 , 0.5 ])

In [17]:
#5
f=np.arange(10,91,10).reshape(3,3)
f

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [38]:
#5a
f[:3,2:]

array([[30],
       [60],
       [90]])

In [40]:
#5b
f[1]

array([40, 50, 60])

In [50]:
#5c
f[0:2,0:2]

array([[10, 20],
       [40, 50]])